[package]
name = "wonderful"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
color-eyre = "0.6.5"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
